# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/igor/Desenvolvimento/neppo/Moonstone/src/moonstone/ilsa/plugins/measure/resources/ui/qt/rulerproperties.ui'
#
# Created: Mon Apr  2 16:53:15 2012
#      by: pyside-uic 0.2.11 running on PySide 1.0.6
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_RulerProperties(object):
    def setupUi(self, RulerProperties):
        RulerProperties.setObjectName("RulerProperties")
        RulerProperties.resize(212, 334)
        RulerProperties.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/static/default/icon/22x22/edit-select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RulerProperties.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(RulerProperties)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtGui.QWidget(RulerProperties)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtGui.QGridLayout(self.widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.measureLabel = QtGui.QLabel(self.widget)
        self.measureLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.measureLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.measureLabel.setObjectName("measureLabel")
        self.gridLayout_4.addWidget(self.measureLabel, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 2, 0, 1, 1)
        self.deleteRulerButton = QtGui.QPushButton(self.widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/static/default/icon/22x22/edit-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteRulerButton.setIcon(icon1)
        self.deleteRulerButton.setObjectName("deleteRulerButton")
        self.gridLayout_4.addWidget(self.deleteRulerButton, 4, 0, 1, 1)
        self.widget_3 = QtGui.QWidget(self.widget)
        self.widget_3.setMinimumSize(QtCore.QSize(81, 28))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 28))
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_5 = QtGui.QGridLayout(self.widget_3)
        self.gridLayout_5.setContentsMargins(-1, 5, -1, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.fontColorFrame = QtGui.QFrame(self.widget_3)
        self.fontColorFrame.setMaximumSize(QtCore.QSize(16777215, 14))
        self.fontColorFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fontColorFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fontColorFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.fontColorFrame.setObjectName("fontColorFrame")
        self.gridLayout_5.addWidget(self.fontColorFrame, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_3, 3, 1, 1, 1)
        self.newRulerButton = QtGui.QPushButton(self.widget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/static/default/icon/22x22/document-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newRulerButton.setIcon(icon2)
        self.newRulerButton.setObjectName("newRulerButton")
        self.gridLayout_4.addWidget(self.newRulerButton, 4, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget1 = QtGui.QWidget(self.widget)
        self.widget1.setMinimumSize(QtCore.QSize(81, 28))
        self.widget1.setMaximumSize(QtCore.QSize(16777215, 28))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtGui.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(-1, 5, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineColorFrame = QtGui.QFrame(self.widget1)
        self.lineColorFrame.setMinimumSize(QtCore.QSize(60, 0))
        self.lineColorFrame.setMaximumSize(QtCore.QSize(16777215, 14))
        self.lineColorFrame.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.lineColorFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lineColorFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.lineColorFrame.setObjectName("lineColorFrame")
        self.gridLayout_2.addWidget(self.lineColorFrame, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.widget1)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtGui.QWidget(self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(81, 28))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 28))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.widget_2)
        self.gridLayout_3.setContentsMargins(-1, 5, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pointColorFrame = QtGui.QFrame(self.widget_2)
        self.pointColorFrame.setMaximumSize(QtCore.QSize(16777215, 14))
        self.pointColorFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pointColorFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pointColorFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.pointColorFrame.setObjectName("pointColorFrame")
        self.gridLayout_3.addWidget(self.pointColorFrame, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 3, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.rulerGroup = QtGui.QGroupBox(RulerProperties)
        self.rulerGroup.setObjectName("rulerGroup")
        self.verticalLayout.addWidget(self.rulerGroup)

        self.retranslateUi(RulerProperties)
        QtCore.QMetaObject.connectSlotsByName(RulerProperties)

    def retranslateUi(self, RulerProperties):
        RulerProperties.setWindowTitle(QtGui.QApplication.translate("RulerProperties", "Ruler Plugin", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("RulerProperties", "Line color:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("RulerProperties", "Mensure:", None, QtGui.QApplication.UnicodeUTF8))
        self.measureLabel.setText(QtGui.QApplication.translate("RulerProperties", "0 mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("RulerProperties", "Point color:", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteRulerButton.setText(QtGui.QApplication.translate("RulerProperties", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.newRulerButton.setText(QtGui.QApplication.translate("RulerProperties", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("RulerProperties", "Font color", None, QtGui.QApplication.UnicodeUTF8))
        self.rulerGroup.setTitle(QtGui.QApplication.translate("RulerProperties", "Rulers", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    RulerProperties = QtGui.QWidget()
    ui = Ui_RulerProperties()
    ui.setupUi(RulerProperties)
    RulerProperties.show()
    sys.exit(app.exec_())

