# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../src/moonstone/ilsa/plugins/text/resources/ui/qt/textproperties.ui'
#
# Created: Wed May 25 17:14:25 2011
#      by: pyside-uic 0.2.8 running on PySide 1.0.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_TextProperties(object):
    def setupUi(self, TextProperties):
        TextProperties.setObjectName("TextProperties")
        TextProperties.resize(216, 342)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/static/default/icon/22x22/text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TextProperties.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(TextProperties)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtGui.QWidget(TextProperties)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setObjectName("widget")
        self.gridLayout_6 = QtGui.QGridLayout(self.widget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widget_5 = QtGui.QWidget(self.widget)
        self.widget_5.setMinimumSize(QtCore.QSize(81, 28))
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 28))
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_7 = QtGui.QGridLayout(self.widget_5)
        self.gridLayout_7.setContentsMargins(-1, 5, -1, -1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.fontColor = QtGui.QFrame(self.widget_5)
        self.fontColor.setMaximumSize(QtCore.QSize(16777215, 14))
        self.fontColor.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fontColor.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fontColor.setFrameShadow(QtGui.QFrame.Raised)
        self.fontColor.setObjectName("fontColor")
        self.gridLayout_7.addWidget(self.fontColor, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_5, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 1)
        self.newTextButton = QtGui.QPushButton(self.widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/static/default/icon/22x22/document-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newTextButton.setIcon(icon1)
        self.newTextButton.setObjectName("newTextButton")
        self.gridLayout_6.addWidget(self.newTextButton, 7, 1, 1, 1)
        self.deleteTextButton = QtGui.QPushButton(self.widget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/static/default/icon/22x22/edit-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteTextButton.setIcon(icon2)
        self.deleteTextButton.setObjectName("deleteTextButton")
        self.gridLayout_6.addWidget(self.deleteTextButton, 7, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 2, 0, 1, 1)
        self.textField = QtGui.QLineEdit(self.widget)
        self.textField.setObjectName("textField")
        self.gridLayout_6.addWidget(self.textField, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 3, 0, 1, 1)
        self.fontCombo = QtGui.QComboBox(self.widget)
        self.fontCombo.setObjectName("fontCombo")
        self.fontCombo.addItem("")
        self.fontCombo.addItem("")
        self.fontCombo.addItem("")
        self.gridLayout_6.addWidget(self.fontCombo, 3, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 4, 0, 1, 1)
        self.fontSize = QtGui.QSpinBox(self.widget)
        self.fontSize.setMinimum(1)
        self.fontSize.setProperty("value", 12)
        self.fontSize.setObjectName("fontSize")
        self.gridLayout_6.addWidget(self.fontSize, 4, 1, 1, 1)
        self.bold = QtGui.QCheckBox(self.widget)
        self.bold.setObjectName("bold")
        self.gridLayout_6.addWidget(self.bold, 5, 0, 1, 1)
        self.italic = QtGui.QCheckBox(self.widget)
        self.italic.setObjectName("italic")
        self.gridLayout_6.addWidget(self.italic, 5, 1, 1, 1)
        self.visible = QtGui.QCheckBox(self.widget)
        self.visible.setChecked(True)
        self.visible.setObjectName("visible")
        self.gridLayout_6.addWidget(self.visible, 6, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.textGroup = QtGui.QGroupBox(TextProperties)
        self.textGroup.setObjectName("textGroup")
        self.verticalLayout.addWidget(self.textGroup)

        self.retranslateUi(TextProperties)
        QtCore.QMetaObject.connectSlotsByName(TextProperties)

    def retranslateUi(self, TextProperties):
        TextProperties.setWindowTitle(QtGui.QApplication.translate("TextProperties", "Text Plugin", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("TextProperties", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.newTextButton.setText(QtGui.QApplication.translate("TextProperties", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteTextButton.setText(QtGui.QApplication.translate("TextProperties", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("TextProperties", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("TextProperties", "Font", None, QtGui.QApplication.UnicodeUTF8))
        self.fontCombo.setItemText(0, QtGui.QApplication.translate("TextProperties", "Arial", None, QtGui.QApplication.UnicodeUTF8))
        self.fontCombo.setItemText(1, QtGui.QApplication.translate("TextProperties", "Courier", None, QtGui.QApplication.UnicodeUTF8))
        self.fontCombo.setItemText(2, QtGui.QApplication.translate("TextProperties", "Times", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("TextProperties", "Font Size", None, QtGui.QApplication.UnicodeUTF8))
        self.bold.setText(QtGui.QApplication.translate("TextProperties", "Bold", None, QtGui.QApplication.UnicodeUTF8))
        self.italic.setText(QtGui.QApplication.translate("TextProperties", "Italic", None, QtGui.QApplication.UnicodeUTF8))
        self.visible.setText(QtGui.QApplication.translate("TextProperties", "Visible", None, QtGui.QApplication.UnicodeUTF8))
        self.textGroup.setTitle(QtGui.QApplication.translate("TextProperties", "Texts", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
import resources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    TextProperties = QtGui.QWidget()
    ui = Ui_TextProperties()
    ui.setupUi(TextProperties)
    TextProperties.show()
    sys.exit(app.exec_())

