# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/igorznt/Desenvolvimento/neppo/Moonstone/src/resources/ui/qt/mainwindow.ui'
#
# Created: Thu Sep 27 18:15:10 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(548, 393)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/static/default/icon/22x22/moonstone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBarActions = QtGui.QToolBar(MainWindow)
        self.toolBarActions.setIconSize(QtCore.QSize(32, 32))
        self.toolBarActions.setObjectName("toolBarActions")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarActions)
        self.toolProperties = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolProperties.sizePolicy().hasHeightForWidth())
        self.toolProperties.setSizePolicy(sizePolicy)
        self.toolProperties.setMinimumSize(QtCore.QSize(94, 119))
        self.toolProperties.setWindowIcon(icon)
        self.toolProperties.setObjectName("toolProperties")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 210, 274))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.toolProperties.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.toolProperties)
        self.toolBarTools = QtGui.QToolBar(MainWindow)
        self.toolBarTools.setIconSize(QtCore.QSize(32, 32))
        self.toolBarTools.setObjectName("toolBarTools")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarTools)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 548, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/static/default/icon/48x48/document-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon1)
        self.actionNew.setObjectName("actionNew")
        self.actionAbout = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/static/default/icon/22x22/moonstone-about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon2)
        self.actionAbout.setObjectName("actionAbout")
        self.actionLicense = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/static/default/icon/22x22/help-about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLicense.setIcon(icon3)
        self.actionLicense.setObjectName("actionLicense")
        self.actionRecentProjects = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/static/default/icon/22x22/document-open-recent.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRecentProjects.setIcon(icon4)
        self.actionRecentProjects.setObjectName("actionRecentProjects")
        self.actionSave = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/static/default/icon/48x48/document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon5)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/static/default/icon/22x22/document-save-as.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveAs.setIcon(icon6)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionPrint = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/static/default/icon/22x22/document-print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon7)
        self.actionPrint.setAutoRepeat(True)
        self.actionPrint.setObjectName("actionPrint")
        self.actionClose = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/static/default/icon/22x22/window-close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon8)
        self.actionClose.setObjectName("actionClose")
        self.actionQuit = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/static/default/icon/22x22/application-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon9)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSaveAll = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/static/default/icon/22x22/document-save-all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveAll.setIcon(icon10)
        self.actionSaveAll.setObjectName("actionSaveAll")
        self.actionOpenProject = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/static/default/icon/48x48/project-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenProject.setIcon(icon11)
        self.actionOpenProject.setObjectName("actionOpenProject")
        self.actionPreferences = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/static/default/icon/22x22/configure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreferences.setIcon(icon12)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionHelpContents = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/static/default/icon/22x22/help-contents.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelpContents.setIcon(icon13)
        self.actionHelpContents.setObjectName("actionHelpContents")
        self.actionReleaseNotes = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/static/default/icon/22x22/im-status-message-edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReleaseNotes.setIcon(icon14)
        self.actionReleaseNotes.setObjectName("actionReleaseNotes")
        self.actionReportBugs = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/static/default/icon/22x22/tools-report-bug.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReportBugs.setIcon(icon15)
        self.actionReportBugs.setObjectName("actionReportBugs")
        self.actionCheckForUpdates = QtGui.QAction(MainWindow)
        self.actionCheckForUpdates.setObjectName("actionCheckForUpdates")
        self.actionSplitLeftNew = QtGui.QAction(MainWindow)
        self.actionSplitLeftNew.setChecked(False)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/static/default/icon/48x48/view-right-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSplitLeftNew.setIcon(icon16)
        self.actionSplitLeftNew.setObjectName("actionSplitLeftNew")
        self.actionSplitLeftClose = QtGui.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/static/default/icon/48x48/view-left-close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSplitLeftClose.setIcon(icon17)
        self.actionSplitLeftClose.setObjectName("actionSplitLeftClose")
        self.actionFullScreen = QtGui.QAction(MainWindow)
        self.actionFullScreen.setCheckable(True)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/static/default/icon/22x22/view-fullscreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFullScreen.setIcon(icon18)
        self.actionFullScreen.setObjectName("actionFullScreen")
        self.toolBarActions.addAction(self.actionNew)
        self.toolBarActions.addAction(self.actionOpenProject)
        self.toolBarActions.addAction(self.actionSave)
        self.toolBarActions.addSeparator()
        self.toolBarActions.addAction(self.actionSplitLeftNew)
        self.toolBarActions.addAction(self.actionSplitLeftClose)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpenProject)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuView.addSeparator()
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionFullScreen)
        self.menuView.addSeparator()
        self.menuHelp.addAction(self.actionHelpContents)
        self.menuHelp.addAction(self.actionReleaseNotes)
        self.menuHelp.addAction(self.actionReportBugs)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionCheckForUpdates)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionLicense)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Moonstone :: MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarActions.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Action Window", None, QtGui.QApplication.UnicodeUTF8))
        self.toolProperties.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Tool Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarTools.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "&View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "&Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "&Import DICOMs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setIconText(QtGui.QApplication.translate("MainWindow", "Import DICOMs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setToolTip(QtGui.QApplication.translate("MainWindow", "Import DICOMs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "&About Moonstone", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLicense.setText(QtGui.QApplication.translate("MainWindow", "&License", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecentProjects.setText(QtGui.QApplication.translate("MainWindow", "&Recent Projects", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setText(QtGui.QApplication.translate("MainWindow", "Save &As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setText(QtGui.QApplication.translate("MainWindow", "&Print", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "&Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAll.setText(QtGui.QApplication.translate("MainWindow", "Save A&ll..", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAll.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenProject.setText(QtGui.QApplication.translate("MainWindow", "&Import Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenProject.setIconText(QtGui.QApplication.translate("MainWindow", "Import Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenProject.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("MainWindow", "Prefere&nces", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setIconText(QtGui.QApplication.translate("MainWindow", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelpContents.setText(QtGui.QApplication.translate("MainWindow", "&Help Contents", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReleaseNotes.setText(QtGui.QApplication.translate("MainWindow", "Release &Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReportBugs.setText(QtGui.QApplication.translate("MainWindow", "&Report Bugs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCheckForUpdates.setText(QtGui.QApplication.translate("MainWindow", "Check f&or Updates...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSplitLeftNew.setText(QtGui.QApplication.translate("MainWindow", "&Show side window", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSplitLeftClose.setText(QtGui.QApplication.translate("MainWindow", "&Hide side window", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFullScreen.setText(QtGui.QApplication.translate("MainWindow", "&Fullscreen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFullScreen.setShortcut(QtGui.QApplication.translate("MainWindow", "F11", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

